### PR TITLE
Fix `payload_data` in EventHeartbeatPayload

### PR DESCRIPTION
**Pull request by univerone**
when I run ding-dong-bot.py for first time, the following error message came out as I mentioned in another issue [#15](https://github.com/wechaty/python-wechaty-getting-started/issues/15)
```
TypeError: __init__() got an unexpected keyword argument 'type'
```

the structure of payload_data is following:
```
{'data': {'code': 0, 'url': 'https://login.weixin.qq.com/qrcode/XXXXXX=='}, 'type': 'scan', 'timeout': 60000}
```
so based on same issue [#6](https://github.com/wechaty/python-wechaty-puppet/issues/6)  and pr #7 , I add the following code to keep only one key `data` in payload_data:
```
payload_data = {'data':payload_data['data']}
```

### CODE REVIEW

**Comment by wj-Mcat** [comment]
It seems that your solution is better.

**Comment by huan** [comment]
Hi @univerone ! Thank you for your contribution!

I have invited you to join our Contributors Team on GitHub Wechaty Org, please follow the below message to accept it:

> You've invited Jiang Shanshan to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

And we have a WeChat group only for our contributors, I'd like to ask you to join us. If you are interested to join, please contact @lijiarui and you will be invited.

**Comment by univerone** [comment]
Hi @huan  Thank you!

**Comment by lijiarui** [comment]
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://github.com/wechaty/wechaty/wiki/Contributors), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty

**Pull request merged**
