### PR TITLE
fix bug of issue: wechaty/python-wechaty#120, which caused by FileBox…

### PR DESCRIPTION
**Pull request by YangTe1**
fix bug of issue: wechaty/python-wechaty#120, which caused by FileBoxType difference

之前那个链接为了弄CLA要改以前所有commit的user和email，不小心搞崩了，重开了一个pull request

### CODE REVIEW

**Comment by YangTe1** [comment]
Link to  [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16)

不好意思，之前那个链接为了弄CLA要改之前commit的user和email，不小心搞崩了，重开了一个pull request @wj-Mcat

**Comment by wj-Mcat** [comment]
There are many types of message, this code is not robust. We provide a [`from_json`](https://github.com/wechaty/python-wechaty-puppet/blob/master/src/wechaty_puppet/file_box/file_box.py#L281) method to hand the object converting things.

Plese use this method to convert filebox json object. Thanks a lot.

**Comment by YangTe1** [comment]
Ya, that's a better way.

**Review by wj-Mcat — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Hello @YangTe1 , thank you very much for sending this pull request for improving our Python Wechaty codebase!

I have sent you an invitation for joining our @wechaty/contributors team, please accept it by visiting <https://github.com/wechaty>

> You've invited YangTe1 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

And we also have a WeChat group for all Wechaty Contributors, please contact @lijiarui if you'd like to join.

Have a good night!

**Pull request merged**
