### PR TITLE
fix bug of issue: https://github.com/wechaty/python-wechaty/issues/12…

### PR DESCRIPTION
**Pull request by YangTe1**
fix bug of issue: https://github.com/wechaty/python-wechaty/issues/120, which caused by FileBoxType difference

### CODE REVIEW

**Comment by huan** [comment]
Link to https://github.com/wechaty/PMC/issues/16

**Comment by wj-Mcat** [comment]
Please make the `CI` green, so we can merge your code to the master branch. Thanks for your contribution.

**Comment by YangTe1** [comment]
> Please make the `CI` green, so we can merge your code to the master branch. Thanks for your contribution.

Sry, I got caught up in daily work and forgot it.

**Comment by YangTe1** [comment]
> Please make the `CI` green, so we can merge your code to the master branch. Thanks for your contribution.

Sry, I got caught up in daily work and forgot it. 
The CLA I had made, but the commit user still not linked to me. Is it necessary？
image

**Pull request closed without merging**
